DATA SEGMENT
COUNT EQU 08H       ; DEFINE A CONSTANT 'COUNT' WITH THE VALUE 08H
NUM DB 00H,01H      ; DEFINE AN ARRAY 'NUM' WITH TWO INITIAL VALUES: 00H AND 01H
DATA ENDS

CODE SEGMENT
START:
    MOV AX, DATA    ; LOAD THE BASE ADDRESS OF THE 'DATA' SEGMENT INTO AX
    MOV DS, AX      ; COPY THE ADDRESS FROM AX TO DS, INITIALIZING THE DATA SEGMENT
    MOV CL, COUNT   ; LOAD 'COUNT' (08H) INTO CL (LOOP COUNTER)
    SUB CL, 02H     ; SUBTRACT 2 FROM CL (CL = CL - 2), ADJUSTING FOR LOOP ITERATIONS

    MOV SI, OFFSET NUM    ; LOAD THE OFFSET ADDRESS OF 'NUM' INTO SI (SOURCE INDEX)
    MOV AL, [SI]          ; LOAD THE FIRST ELEMENT OF 'NUM' (00H) INTO AL
    INC SI                ; INCREMENT SI TO POINT TO THE NEXT ELEMENT
    MOV BL, [SI]          ; LOAD THE SECOND ELEMENT OF 'NUM' (01H) INTO BL

UP:    
    ADD AL, BL            ; ADD AL AND BL, STORE THE RESULT IN AL
    XCHG AL, BL           ; SWAP THE VALUES OF AL AND BL
    INC SI                ; MOVE SI TO THE NEXT MEMORY LOCATION
    MOV [SI], BL          ; STORE THE UPDATED BL VALUE AT THE NEW SI LOCATION
    DEC CL                ; DECREMENT LOOP COUNTER CL
    JNZ UP                ; IF CL IS NOT ZERO, REPEAT THE LOOP

    MOV AX, 4C00H         ; DOS interrupt to terminate the program
    INT 21H               ; DOS interrupt to terminate program properly

CODE ENDS
END START               ; Properly ending the program with a START label
